### ISSUE TITLE
Not showing learning cards with big steps

### ISSUE THREAD

**Issue by dedu6ka** [HelenFoster/AnkiAddons#1]
Thank you for such an invaluable add-on.  
Now 'they' will not rebuild a deck with Learning cards in it; and  
I will see how soon the Step expires.  

Issue:  
It does not indicate that a Learning card ( with step = 1440 ) is still in the deck, a Filtered deck . 
There is no issue in a Regular deck.  

Good day.

**Comment by HelenFoster** [comment]
Hi, thanks for your comment. I'll look into it.

**Comment by HelenFoster** [comment]
The numbers only show cards due "today". Is it possible that the card in your filtered deck was due tomorrow?
