### ISSUE TITLE
suggested feature: show deck's option group

### ISSUE THREAD

**Issue by B-bit-maker** [HelenFoster/AnkiAddons#10]
Hello, thank you for this addon.
Would it be possible to show also the deck's option group in the main screen?
Thank you.

**Comment by HelenFoster** [comment]
Hi, I'm aiming to keep this one minimalist. https://github.com/Arthur-Milchior/anki-enhance-main-window appears to have that feature.

**Comment by B-bit-maker** [comment]
Ok, thanks.
