### ISSUE TITLE
"onclick handler needs to return false"

### ISSUE THREAD

**Issue by dsc321123** [HelenFoster/AnkiAddons#4]
I'm trying to get this to work with Anki 2.1 and it keeps giving me an error. So far I renamed Deck_Counts_Now_Later.py to __init__.py and placed it in a folder in addons21. I'm new to add-on compatibility issues. Can you please let me know what I am missing? Thank you for this wonderful add-on.

Might it be because I am using 2.1.10?

Error 
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem. 
When you've discovered the add-on that is causing the problem, please report the issue on the add-ons section of our support site. 
Debug info:
Anki 2.1.10 (22d6feed) Python 3.6.7 Qt 5.12.1 PyQt 5.11.3
Platform: Windows 10
Flags: frz=True ao=True sv=1

onclick handler needs to return false

**Comment by HelenFoster** [comment]
I just tried the latest Anki on Windows 10, and it seems to be working for me. Did you get the latest version of Deck_Counts_Now_Later.py from this git repo?

**Comment by dsc321123** [comment]
Thank you for your response. Yes, I just downloaded the latest file from <>Code again and I got the same error as noted above. I also disabled all of my other add-ons to test this. Any suggestions?

**Comment by dsc321123** [comment]
Thank you for your response. Perhaps I am not using the correct file? I downloaded the file associated with [DCNL] Fix learn-ahead; fix Python 3 division. I re-downloaded this file and tried again and got the same error. I also disabled all of my other add-ons. Do you have any suggestions I can try to get it to work?

Thank you again.

**Comment by HelenFoster** [comment]
Can you try on another computer?

**Comment by dsc321123** [comment]
I just tried on a new computer. This time using anki 2.1.11. I got the following error. Not sure what to try next.

Error 
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem. 
When you've discovered the add-on that is causing the problem, please report the issue on the add-ons section of our support site. 
Debug info:
Anki 2.1.11 (3cf770c7) Python 3.6.7 Qt 5.12.1 PyQt 5.11.3
Platform: Windows 10
Flags: frz=True ao=True sv=1

onclick handler needs to return false

**Comment by HelenFoster** [comment]
Hmm, if that was also a new Anki profile on the new computer, I'm not sure what to try. If you had already synced your decks, can you try a new profile too?

**Comment by HelenFoster** [comment]
Could anyone else test this and let us know?

**Comment by HelenFoster** [comment]
@gajewsk2 @MrPiethon could you do me a favour and test this addon out on Anki 2.1? I think it's ugly with the default CSS, and still thinking what's best to do about that (currently using edited CSS in the program folder myself). But the question here is just whether it works or not.

**Comment by HelenFoster** [comment]
@dsc321123 I think I tracked down the issue. Try it now?

Related: https://github.com/dae/anki/commit/14f4107dfda3c75d8e0eeb1c44141ceb962cd3c6

Strangely I still didn't get the error message, but on Anki 2.1.13 on Windows 7, I started having the problem with the deck links not working.

**Comment by dsc321123** [comment]
Will try it and let you know later today. Thank you.
    On Sunday, June 16, 2019, 10:59:15 AM EDT, HelenFoster <notifications@github.com> wrote:  
 
 
@dsc321123 I think I tracked down the issue. Try it now?

Related: dae/anki@14f4107

Strangely I still didn't get the error message, but on Anki 2.1.13 on Windows 7, I started having the problem with the deck links not working.

**Comment by HelenFoster** [comment]
> Will try it and let you know later today. Thank you.

@dsc321123 did you have a chance to try it out? (I'm not seeing any further message from you, though maybe it got lost somehow.)
