### ISSUE TITLE
Adding another column for "Tomorrow"

### ISSUE THREAD

**Issue by adix03** [HelenFoster/AnkiAddons#6]
A column for cards due tomorrow will make an interesting addition to this already useful addon. It also goes with the theme of the addon, "Now/Later/Tomorrow".

**Comment by HelenFoster** [comment]
Hi, I'm aiming to keep this one minimalist. It might be worth asking https://github.com/Arthur-Milchior/anki-enhance-main-window (partly based on DCNL but aiming for a lot of features).
