### ISSUE TITLE
Why are all the counts 0?

### ISSUE THREAD

**Issue by wtfbaku** [HelenFoster/AnkiAddons#7]
Sorry if this is a dumb question, but I'm a bit confused. There is no "countdown" showing for due cards, but that could be because there are none due later today. However, there are no later cards either. 
<img width="658" alt="Screen Shot 2020-03-27 at 5 59 00 PM" src="https://user-images.githubusercontent.com/62775285/77804403-cbaf0f00-7055-11ea-9759-48a8bdadc4e3.png">
Why is this?

**Comment by HelenFoster** [comment]
Hi, that's expected if you're finished for today. Due means "due now" and Later means "due later today".
