### ISSUE TITLE
Change font color

### ISSUE THREAD

**Issue by igorski88** [HelenFoster/AnkiAddons#8]
Where can I change the font color of the "now" row. In dark mode the dark blue font is very hard to see.  Thanks in advance.

**Comment by HelenFoster** [comment]
Hi, are you talking about the update in Anki 2.1.20, "The night mode option in the preferences screen now turns the interface dark as well"? I'll need to see what changed in Anki and update DCNL to match it.

**Comment by HelenFoster** [comment]
The colours should now be the same as in vanilla Anki (and you could change them in Anki's css the same way as without the addon). I'd like to test it a good bit more before putting on AnkiWeb.
